version: '3.5'

services:
    php:
        container_name: php_we_movies
        image: front:7.4
        ports:
            - "9003:9003"
        external_links:
            - postgres
        volumes:
            - .:/var/www/we-movies
            - /var/run/php7-fpm/:/var/run/php7-fpm/
            - ./docker/we-movies.conf:/usr/local/etc/php-fpm.d/we-movies.conf
            - /home/dev/.ssh:/home/dev/.ssh        
        networks:
            - common
            - we-movies
        working_dir: /var/www/we-movies        
        tty: true

networks:
    we-movies:
        external:
            name: we-movies
    common:
        external:
            name : common